#
# Copyright (c) 2024 Intel Corporation.
#
# This work is licensed under the terms of the MIT license.
# For a copy, see <https://opensource.org/licenses/MIT>.
#

bool synchronous_mode false
bool no_rendering_mode false
float64 fixed_delta_seconds
bool substepping true
float64 max_substep_delta_time 0.01
int32 max_substeps 10
float32 max_culling_distance 0.0
bool deterministic_ragdolls false
float32 tile_stream_distance 3000.0
float32 actor_active_distance 2000.0
bool spectator_as_ego true
